apiVersion: v1
kind: Pod
metadata: 
  name : my-pod
labels :
 name: my-pod 
 spce: 
  container: 
     - name: 1con
       image: nginx
       ports:
        - name: 1con 
          containerport: 80
          protocol: TCP
